using System.Collections.Generic;
using UnityEngine;

namespace Unfair.Util
{
	public static class KeyToString
	{
		public static Dictionary<KeyCode, string> KeyMap = new Dictionary<KeyCode, string>()
		{
			{ KeyCode.None, "None" },
			{ KeyCode.Backspace, "Backspace" },
			{ KeyCode.Delete, "Delete"},
			{ KeyCode.Tab, "Tab" },
			{ KeyCode.Clear, "Clear" },
			{ KeyCode.Return, "Enter" },
			{ KeyCode.Pause, "Pause" },
			{ KeyCode.Escape, "Escape" },
			{ KeyCode.Space, "Space" },
			{ KeyCode.Keypad0, "Num 0" },
			{ KeyCode.Keypad1, "Num 1" },
			{ KeyCode.Keypad2, "Num 2" },
			{ KeyCode.Keypad3, "Num 3" },
			{ KeyCode.Keypad4, "Num 4" },
			{ KeyCode.Keypad5, "Num 5" },
			{ KeyCode.Keypad6, "Num 6" },
			{ KeyCode.Keypad7, "Num 7" },
			{ KeyCode.Keypad8, "Num 8" },
			{ KeyCode.Keypad9, "Num 9" },
			{ KeyCode.KeypadPeriod, "Num ." },
			{ KeyCode.KeypadDivide, "Num /" },
			{ KeyCode.KeypadMultiply, "Num *" },
			{ KeyCode.KeypadMinus, "Num -" },
			{ KeyCode.KeypadPlus, "Num +" },
			{ KeyCode.KeypadEnter, "Num Enter" },
			{ KeyCode.KeypadEquals, "Num =" },
			{ KeyCode.UpArrow, "Up" },
			{ KeyCode.DownArrow, "Down" },
			{ KeyCode.RightArrow, "Right" },
			{ KeyCode.LeftArrow, "Left" },
			{ KeyCode.Insert, "Insert" },
			{ KeyCode.Home, "Home" },
			{ KeyCode.End, "End" },
			{ KeyCode.PageUp, "Page Up" },
			{ KeyCode.PageDown, "Page Down" },
			{ KeyCode.F1, "F1" },
			{ KeyCode.F2, "F2" },
			{ KeyCode.F3, "F3" },
			{ KeyCode.F4, "F4" },
			{ KeyCode.F5, "F5" },
			{ KeyCode.F6, "F6" },
			{ KeyCode.F7, "F7" },
			{ KeyCode.F8, "F8" },
			{ KeyCode.F9, "F9" },
			{ KeyCode.F10, "F10" },
			{ KeyCode.F11, "F11" },
			{ KeyCode.F12, "F12" },
			{ KeyCode.F13, "F13" },
			{ KeyCode.F14, "F14" },
			{ KeyCode.F15, "F15" },
			{ KeyCode.Alpha0, "0" },
			{ KeyCode.Alpha1, "1" },
			{ KeyCode.Alpha2, "2" },
			{ KeyCode.Alpha3, "3" },
			{ KeyCode.Alpha4, "4" },
			{ KeyCode.Alpha5, "5" },
			{ KeyCode.Alpha6, "6" },
			{ KeyCode.Alpha7, "7" },
			{ KeyCode.Alpha8, "8" },
			{ KeyCode.Alpha9, "9" },
			{ KeyCode.Exclaim, "!" },
			{ KeyCode.DoubleQuote, "\"" },
			{ KeyCode.Hash, "#" },
			{ KeyCode.Dollar, "$" },
			{ KeyCode.Percent, "%" },
			{ KeyCode.Ampersand, "&" },
			{ KeyCode.Quote, "'" },
			{ KeyCode.LeftParen, "(" },
			{ KeyCode.RightParen, ")" },
			{ KeyCode.Asterisk, "*" },
			{ KeyCode.Plus, "+" },
			{ KeyCode.Comma, "," },
			{ KeyCode.Minus, "-" },
			{ KeyCode.Period, "." },
			{ KeyCode.Slash, "/" },
			{ KeyCode.Colon, ":" },
			{ KeyCode.Semicolon, ";" },
			{ KeyCode.Less, "<" },
			{ KeyCode.Equals, "=" },
			{ KeyCode.Greater, ">" },
			{ KeyCode.Question, "?" },
			{ KeyCode.At, "@" },
			{ KeyCode.LeftBracket, "[" },
			{ KeyCode.Backslash, "\\" },
			{ KeyCode.RightBracket, "]" },
			{ KeyCode.Caret, "^" },
			{ KeyCode.Underscore, "_" },
			{ KeyCode.BackQuote, "`" },
			{ KeyCode.A, "A" },
			{ KeyCode.B, "B" },
			{ KeyCode.C, "C" },
			{ KeyCode.D, "D" },
			{ KeyCode.E, "E" },
			{ KeyCode.F, "F" },
			{ KeyCode.G, "G" },
			{ KeyCode.H, "H" },
			{ KeyCode.I, "I" },
			{ KeyCode.J, "J" },
			{ KeyCode.K, "K" },
			{ KeyCode.L, "L" },
			{ KeyCode.M, "M" },
			{ KeyCode.N, "N" },
			{ KeyCode.O, "O" },
			{ KeyCode.P, "P" },
			{ KeyCode.Q, "Q" },
			{ KeyCode.R, "R" },
			{ KeyCode.S, "S" },
			{ KeyCode.T, "T" },
			{ KeyCode.U, "U" },
			{ KeyCode.V, "V" },
			{ KeyCode.W, "W" },
			{ KeyCode.X, "X" },
			{ KeyCode.Y, "Y" },
			{ KeyCode.Z, "Z" },
			{ KeyCode.LeftCurlyBracket, "{" },
			{ KeyCode.Pipe, "|" },
			{ KeyCode.RightCurlyBracket, "}" },
			{ KeyCode.Tilde, "~" },
			{ KeyCode.Numlock, "Num Lock" },
			{ KeyCode.CapsLock, "Caps Lock" },
			{ KeyCode.ScrollLock, "Scroll Lock" },
			{ KeyCode.RightShift, "Right Shift" },
			{ KeyCode.LeftShift, "Left Shift" },
			{ KeyCode.RightControl, "Right Control" },
			{ KeyCode.LeftControl, "Left Control" },
			{ KeyCode.RightAlt, "Right Alt" },
			{ KeyCode.LeftAlt, "Left Alt" },
			{ KeyCode.LeftWindows, "Windows" },
			{ KeyCode.RightWindows, "Right Windows" },
			{ KeyCode.AltGr, "Right Alt" },
			{ KeyCode.Help, "Help" },
			{ KeyCode.Print, "Print" },
			{ KeyCode.SysReq, "Sys Req" },
			{ KeyCode.Break, "Break" },
			{ KeyCode.Menu, "Menu" },
			{ KeyCode.Mouse0, "Left Click" },
			{ KeyCode.Mouse1, "Right Click" },
			{ KeyCode.Mouse2, "Middle Click" },
			{ KeyCode.Mouse3, "Mouse 3" },
			{ KeyCode.Mouse4, "Mouse 4" },
			{ KeyCode.Mouse5, "Mouse 5" },
			{ KeyCode.Mouse6, "Mouse 6" }
		};
	}
}